export default function LocalSslDocsPage() {
  return (
    <div className="px-6 pt-32 pb-24">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center gap-3 mb-6">
          <a href="/docs" className="text-sm text-white/30 hover:text-white/50 transition-colors">Docs</a>
          <span className="text-white/20">/</span>
          <span className="text-sm text-white/60">local-ssl</span>
        </div>

        <h1 className="text-4xl sm:text-5xl font-bold tracking-tighter mb-4">
          <span className="text-[#34d399]">local-ssl</span>
        </h1>
        <p className="text-lg text-white/40 mb-12 max-w-[50ch]">
          Generate locally-trusted HTTPS certificates for development. Pure Rust, no OpenSSL dependency.
        </p>

        <Section title="Installation">
          <CodeBlock>{`cargo install local-ssl

# Prerequisites (for system trust):
# macOS: (bundled)
# Linux: update-ca-certificates
# Windows: certutil`}</CodeBlock>
        </Section>

        <Section title="Quick start">
          <Steps steps={[
            { label: 'Initialize CA', code: 'sudo local-ssl init' },
            { label: 'Generate cert', code: 'sudo local-ssl generate myapp.test' },
            { label: 'Test HTTPS', code: 'curl --cacert /etc/local-ssl/ca-cert.pem https://myapp.test/' },
            { label: 'Generate with SANs', code: 'sudo local-ssl generate api.test www.test' },
          ]} />
        </Section>

        <Section title="Commands">
          <div className="space-y-3">
            <CmdRow cmd="local-ssl init" desc="Initialize CA and install system trust" />
            <CmdRow cmd="local-ssl generate <domains>" desc="Generate HTTPS certificates" opts="--output" />
            <CmdRow cmd="local-ssl list" desc="List all generated certificates" />
            <CmdRow cmd="local-ssl show <domain>" desc="Show certificate details" />
            <CmdRow cmd="local-ssl trust" desc="Reinstall CA system trust" />
            <CmdRow cmd="local-ssl status" desc="Show CA and certificate status" />
            <CmdRow cmd="local-ssl telemetry status" desc="View telemetry settings" />
          </div>
        </Section>

        <Section title="CA Management">
          <p className="text-sm text-white/50 leading-relaxed mb-4">
            The Certificate Authority is generated once and stored at <code className="text-white/70">/etc/local-ssl/</code>.
            The CA certificate is valid for 10 years. Server certificates are valid for 1 year.
          </p>
          <CodeBlock>{`# Check CA status
local-ssl status

# Reinstall system trust
sudo local-ssl trust

# CA files:
#   /etc/local-ssl/ca-key.pem
#   /etc/local-ssl/ca-cert.pem
#   /etc/local-ssl/certs/<domain>/`}</CodeBlock>
        </Section>

        <Section title="Integration with local-dns">
          <p className="text-sm text-white/50 leading-relaxed mb-4">
            local-ssl pairs seamlessly with local-dns for complete local development infrastructure.
          </p>
          <CodeBlock>{`# 1. Add DNS entry
local-dns add myapp.test 127.0.0.1

# 2. Generate HTTPS cert
sudo local-ssl generate myapp.test

# 3. Access via HTTPS
curl https://myapp.test/

# 4. Your local server
node server.js --key /etc/local-ssl/certs/myapp.test/key.pem \\
  --cert /etc/local-ssl/certs/myapp.test/cert.pem`}</CodeBlock>
        </Section>

        <Section title="Security Notes">
          <div className="space-y-3 text-sm text-white/50 leading-relaxed">
            <p>All certificates generated by local-ssl are for <strong className="text-white/70">local development only</strong>.
            The CA certificate should never be distributed or trusted outside your development machine.</p>
            <p>The tool uses <strong className="text-white/70">rcgen</strong> for certificate generation — a pure Rust implementation
            with no OpenSSL FFI dependency. Keys are stored as PEM files with 600 permissions.</p>
          </div>
        </Section>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-12">
      <h2 className="text-xl font-semibold tracking-tight mb-5">{title}</h2>
      {children}
    </div>
  )
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="rounded-2xl border border-white/[0.04] bg-white/[0.02] p-5 overflow-x-auto">
      <code className="font-mono text-sm text-white/60 leading-relaxed whitespace-pre">{children}</code>
    </pre>
  )
}

function Steps({ steps }: { steps: { label: string; code: string }[] }) {
  return (
    <div className="space-y-3">
      {steps.map((s, i) => (
        <div key={i} className="flex items-start gap-4">
          <div className="w-6 h-6 rounded-full bg-[#34d399]/10 border border-[#34d399]/20 flex items-center justify-center shrink-0 mt-0.5">
            <span className="text-xs font-mono text-[#34d399]">{i + 1}</span>
          </div>
          <div className="flex-1">
            <p className="text-sm font-medium text-white/70 mb-1">{s.label}</p>
            <pre className="rounded-xl border border-white/[0.04] bg-white/[0.02] px-4 py-2.5 overflow-x-auto">
              <code className="font-mono text-sm text-white/50"><span className="text-white/20">$ </span>{s.code}</code>
            </pre>
          </div>
        </div>
      ))}
    </div>
  )
}

function CmdRow({ cmd, desc, opts }: { cmd: string; desc: string; opts?: string }) {
  return (
    <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-4 py-2">
      <code className="font-mono text-sm text-white/70 sm:w-[32rem] shrink-0">{cmd}</code>
      <span className="text-sm text-white/40">{desc}</span>
      {opts && <span className="text-xs text-white/20 font-mono">{opts}</span>}
    </div>
  )
}
